FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

RUN mkdir -p /app/export_results

ENV OUTPUT_DIR=/app/export_results

CMD ["python", "export_legacy_order_history_tool.py"]