apiVersion: v1
kind: Pod
metadata:
  name: fix-vertex-report-tool
  namespace: prod-consumer
spec:
  containers:
    - name: python
      image: python:3.12-slim
      command: [ "sleep", "infinity" ]  # 保持容器常驻
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 500m
          memory: 1Gi
  restartPolicy: Always
