FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

RUN mkdir -p /app/export_refund_history

ENV OUTPUT_DIR=/app/export_refund_history

CMD ["python", "export_refund_history_tool.py"]